import type { Metadata } from "next";
import { Geist, Geist_Mono, Mitr } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const mits = Mitr({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-mits",
});

export const metadata: Metadata = {
  title: "SPF | Space Fight 🚀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mits.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
